import React, { useState, useEffect, useCallback, useMemo } from 'react';
import {
  View, Text, StyleSheet, ScrollView, Pressable,
  Dimensions, ActivityIndicator, Alert, Image,
} from 'react-native';
import { MaterialIcons } from '@expo/vector-icons';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { LinearGradient } from 'expo-linear-gradient';
import { Svg, Path, G, Text as SvgText, Defs, LinearGradient as SvgGradient, Stop, Circle, Rect } from 'react-native-svg';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { dataService } from '../../services/dataService';
import { colors, spacing, shadows, borderRadius } from '../../constants/theme';
import { format, startOfWeek, startOfMonth, isAfter, subDays } from 'date-fns';
import { useAuth } from '../../hooks/useAuth';

const { width } = Dimensions.get('window');

type Period = 'Today' | 'Week' | 'Month' | 'All';

// ─── Generate HTML for PDF ───────────────────────────────────
const buildHTML = (logs: any[], period: string, stats: any) => `
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: 'Helvetica Neue', sans-serif; margin: 0; padding: 32px; background: #F8FAFC; color: #0F172A; }
  h1 { font-size: 26px; margin: 0 0 4px; }
  .sub { font-size: 13px; color: #64748B; margin-bottom: 24px; }
  .summary { display: flex; gap: 16px; margin-bottom: 24px; }
  .stat-box { background: #EEF2FF; padding: 14px 20px; border-radius: 12px; flex: 1; text-align: center; }
  .stat-val { font-size: 28px; font-weight: bold; color: #4F46E5; }
  .stat-lbl { font-size: 11px; color: #64748B; text-transform: uppercase; }
  table { width: 100%; border-collapse: collapse; background: #FFF; border-radius: 12px; overflow: hidden; }
  th { background: #0F172A; color: #FFF; padding: 12px 16px; font-size: 12px; text-align: left; }
  td { padding: 12px 16px; border-bottom: 1px solid #F1F5F9; font-size: 13px; }
  .good { color: #059669; font-weight: bold; }
  .bad { color: #EF4444; font-weight: bold; }
  .footer { margin-top: 24px; font-size: 11px; color: #94A3B8; text-align: center; }
</style>
</head>
<body>
  <h1>Dean Attendance Report</h1>
  <p class="sub">Period: ${period} &nbsp;·&nbsp; Generated ${format(new Date(), 'dd MMM yyyy, hh:mm a')}</p>
  <div class="summary">
    <div class="stat-box"><div class="stat-val">${stats.totalClasses}</div><div class="stat-lbl">Classes</div></div>
    <div class="stat-box"><div class="stat-val">${stats.presentToday}</div><div class="stat-lbl">Present Today</div></div>
    <div class="stat-box"><div class="stat-val">${stats.absentToday}</div><div class="stat-lbl">Absent Today</div></div>
  </div>
  <table>
    <tr><th>Class</th><th>Date</th><th>Marked By</th><th>Present</th><th>Absent</th><th>On Duty</th><th>Rate</th></tr>
    ${logs.map(l => {
      const r = l.total > 0 ? Math.round(((l.present + l.onDuty) / l.total) * 100) : 0;
      return `<tr>
        <td>${l.className}</td>
        <td>${l.date}</td>
        <td>${l.markedBy}</td>
        <td class="good">${l.present}</td>
        <td class="bad">${l.absent}</td>
        <td>${l.onDuty}</td>
        <td class="${r >= 75 ? 'good' : 'bad'}">${r}%</td>
      </tr>`;
    }).join('')}
  </table>
  <p class="footer">This report was auto-generated by the Attendance Management System.</p>
</body>
</html>`;

export default function DeanReports() {
  const insets = useSafeAreaInsets();
  const { user, loading: authLoading } = useAuth();
  const [period, setPeriod] = useState<Period>('Week');
  const [selectedDay, setSelectedDay] = useState<string>(format(new Date(), 'yyyy-MM-dd'));
  const [allLogs, setAllLogs] = useState<any[]>([]);
  const [stats, setStats] = useState({ totalClasses: 0, presentToday: 0, absentToday: 0, onDutyToday: 0 });
  const [loading, setLoading] = useState(true);
  const [downloading, setDownloading] = useState(false);

  const fetchData = useCallback(async () => {
    if (authLoading || !user) return;
    try {
      setLoading(true);
      const [logs, st] = await Promise.all([
        dataService.getAttendanceLogs(200),
        dataService.getStatistics(),
      ]);
      setAllLogs(logs);
      setStats(st);
      
      const latestLog = logs[0]?.date || format(new Date(), 'yyyy-MM-dd');
      setSelectedDay(latestLog.substring(0, 10));
    } catch {
    } finally {
      setLoading(false);
    }
  }, [user, authLoading]);

  useEffect(() => {
    if (!authLoading && user) {
      fetchData();
      const subAttendance = dataService.subscribeToTable('attendance_records', fetchData);
      const subClasses = dataService.subscribeToTable('classes', fetchData);
      
      return () => {
        subAttendance?.unsubscribe();
        subClasses?.unsubscribe();
      };
    }
  }, [fetchData, authLoading, user]);

  // Filter logs by period
  const filteredLogs = allLogs.filter(l => {
    try {
      const d = new Date(l.date);
      const now = new Date();
      if (period === 'Today') return format(d, 'yyyy-MM-dd') === format(now, 'yyyy-MM-dd');
      if (period === 'Week') return isAfter(d, startOfWeek(now, { weekStartsOn: 1 }));
      if (period === 'Month') return isAfter(d, startOfMonth(now));
      return true; // All
    } catch { return true; }
  });

  // Records for focus (either the whole period or a specific selected day)
  const focusLogs = filteredLogs.filter(l => (l.date || '').substring(0, 10) === selectedDay);

  // Group by class (for the selected focus day)
  const classSummary: Record<string, { logs: any[]; className: string; markedBy: string; advisorImage?: string }> = {};
  focusLogs.forEach(l => {
    const cn = l.className || 'Unknown';
    if (!classSummary[cn]) {
      classSummary[cn] = { logs: [], className: cn, markedBy: l.markedBy, advisorImage: l.advisorImage };
    }
    classSummary[cn].logs.push(l);
  });

  const classReports = Object.values(classSummary).map(c => {
    const totalP = c.logs.reduce((s, l) => s + (l.present || 0), 0);
    const totalA = c.logs.reduce((s, l) => s + (l.absent || 0), 0);
    const totalO = c.logs.reduce((s, l) => s + (l.onDuty || 0), 0);
    const total = totalP + totalA + totalO;
    const rate = total > 0 ? Math.round(((totalP + totalO) / total) * 100) : 0;
    return { 
      className: c.className, 
      markedBy: c.markedBy, 
      advisorImage: c.advisorImage,
      present: totalP, 
      absent: totalA, 
      onDuty: totalO, 
      total, 
      rate, 
      sessions: c.logs.length 
    };
  });

  // We calculate totals for the focus day
  const dayTotals = focusLogs.reduce((s, l) => ({
    p: s.p + (l.present || 0),
    a: s.a + (l.absent || 0),
    o: s.o + (l.onDuty || 0),
    tot: s.tot + (l.totalStudents || (l.present + l.absent + (l.onDuty || 0))),
    sess: s.sess + 1
  }), { p: 0, a: 0, o: 0, tot: 0, sess: 0 });

  const dayGrandRate = dayTotals.tot > 0
    ? Math.round(((dayTotals.p + dayTotals.o) / dayTotals.tot) * 100) : 0;

  // Trend line from daily totals - Custom grouping based on period
  const dailyPoints = useMemo(() => {
    const now = new Date();
    
    // CASE 1: TODAY - Only today's point
    if (period === 'Today') {
      const dKey = format(now, 'yyyy-MM-dd');
      let p=0, a=0, o=0;
      allLogs.forEach(l => {
        if ((l.date || l.timestamp || '').startsWith(dKey)) {
          p += (l.present || 0); a += (l.absent || 0); o += (l.onDuty || 0);
        }
      });
      const t = p + a + o;
      return [{
        rate: t > 0 ? Math.round(((p + o) / t) * 100) : 0,
        label: format(now, 'dd MMM'),
        day: format(now, 'EEE'),
        fullDate: dKey
      }];
    }

    // CASE 2: WEEK - Last 7 days with short names and dates
    if (period === 'Week') {
      const days = [];
      for (let i = 6; i >= 0; i--) {
        const d = subDays(now, i);
        const dKey = format(d, 'yyyy-MM-dd');
        let p=0, a=0, o=0;
        allLogs.forEach(l => {
          if ((l.date || l.timestamp || '').startsWith(dKey)) {
            p += (l.present || 0); a += (l.absent || 0); o += (l.onDuty || 0);
          }
        });
        const t = p + a + o;
        days.push({
          rate: t > 0 ? Math.round(((p + o) / t) * 100) : 0,
          label: format(d, 'EEE dd').toLowerCase(), // e.g. fri 27
          day: format(d, 'EEE'),
          fullDate: dKey
        });
      }
      return days;
    }

    // CASE 3: MONTH - Four Weeks aggregation
    if (period === 'Month') {
      const weeks = [];
      for (let i = 3; i >= 0; i--) {
        let p=0, a=0, o=0;
        const weekEnd = subDays(now, i * 7);
        const weekStart = subDays(weekEnd, 6);
        let weekLabel = `W${4-i} (${format(weekStart, 'dd')}-${format(weekEnd, 'dd')})`; 
        
        allLogs.forEach(l => {
          const logDate = new Date(l.date || l.timestamp);
          if (isAfter(logDate, subDays(weekStart, 1)) && !isAfter(logDate, weekEnd)) {
            p += (l.present || 0); a += (l.absent || 0); o += (l.onDuty || 0);
          }
        });
        const t = p + a + o;
        weeks.push({
          rate: t > 0 ? Math.round(((p + o) / t) * 100) : 0,
          label: weekLabel,
          day: weekLabel,
          fullDate: format(weekEnd, 'yyyy-MM-dd')
        });
      }
      return weeks;
    }

    // FALLBACK: ALL - Last 30 days daily with dates
    const dailyMap: Record<string, {p: number, a: number, o: number, date: string}> = {};
    for (let i = 30; i >= 0; i--) {
      const dKey = format(subDays(now, i), 'yyyy-MM-dd');
      dailyMap[dKey] = { p: 0, a: 0, o: 0, date: dKey };
    }
    allLogs.forEach(l => {
      const dKey = (l.date || l.timestamp || '').substring(0, 10);
      if (dailyMap[dKey]) {
        dailyMap[dKey].p += (l.present || 0);
        dailyMap[dKey].a += (l.absent || 0);
        dailyMap[dKey].o += (l.onDuty || 0);
      }
    });

    return Object.values(dailyMap).sort((a,b) => a.date.localeCompare(b.date)).map(v => {
      const t = v.p + v.a + v.o;
      const rate = t > 0 ? Math.round(((v.p + v.o) / t) * 100) : 0;
      const d = new Date(v.date);
      return {
        rate,
        label: format(d, 'EEE dd').toLowerCase(),
        day: format(d, 'EEE'),
        fullDate: v.date
      };
    });
  }, [allLogs, period]);

  const svgW = width - 48; // Wider chart
  const CHART_HEIGHT = 160;
  const PADDING = 20;

  const getX = useCallback((index: number) => {
    if (dailyPoints.length <= 1) return svgW / 2;
    return PADDING + (index / (dailyPoints.length - 1)) * (svgW - PADDING * 2);
  }, [dailyPoints.length, svgW]);

  const getY = useCallback((rate: number) => {
    return (CHART_HEIGHT - 45) - (rate / 100) * (CHART_HEIGHT - 70) + 5;
  }, []);

  const points = useMemo(() => dailyPoints.map((p, i) => ({ x: getX(i), y: getY(p.rate) })), [dailyPoints, getX, getY]);

  const linePath = useMemo(() => {
    if (points.length === 0) return '';
    return points.map((p, i) => `${i === 0 ? 'M' : 'L'} ${p.x} ${p.y}`).join(' ');
  }, [points]);

  const areaPath = useMemo(() => {
    if (points.length === 0) return '';
    const baseLine = CHART_HEIGHT - 30;
    // Connect from Origin (Left Baseline) -> Line -> Right Baseline -> Back to Origin
    return `M ${PADDING} ${baseLine} ${linePath.replace('M', 'L')} L ${points[points.length - 1].x} ${baseLine} Z`;
  }, [points, linePath]);

  const downloadReport = async () => {
    try {
      setDownloading(true);
      const html = buildHTML(filteredLogs, period, stats);
      const { uri } = await Print.printToFileAsync({ html });
      const canShare = await Sharing.isAvailableAsync();
      if (canShare) {
        await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
      } else {
        Alert.alert('Downloaded', `Report saved to:\n${uri}`);
      }
    } catch (e: any) {
      Alert.alert('Error', e?.message || 'Failed to generate report.');
    } finally { setDownloading(false); }
  };

  const downloadClassReport = async (cls: typeof classReports[0]) => {
    try {
      const html = buildHTML(filteredLogs.filter(l => l.className === cls.className), period, {
        totalClasses: 1, presentToday: cls.present, absentToday: cls.absent,
      });
      const { uri } = await Print.printToFileAsync({ html });
      const canShare = await Sharing.isAvailableAsync();
      if (canShare) await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
    } catch (e: any) { Alert.alert('Error', e?.message || 'Failed.'); }
  };

  return (
    <View style={styles.root}>
      {/* Header */}
      <LinearGradient colors={['#0F172A', '#1E293B']}
        style={[styles.header, { paddingTop: insets.top + 8 }]}>
        <View style={styles.topBar}>
          <View>
            <Text style={styles.headerSub}>Dean Portal</Text>
            <Text style={styles.headerTitle}>Reports & Analytics</Text>
          </View>
          <Pressable onPress={downloadReport} style={[styles.dlBtn, downloading && { opacity: 0.6 }]} disabled={downloading}>
            {downloading
              ? <ActivityIndicator color="#FFF" size="small" />
              : <>
                  <MaterialIcons name="download" size={18} color="#FFF" />
                  <Text style={styles.dlBtnText}>Export All</Text>
                </>
            }
          </Pressable>
        </View>

        {/* Period Filters */}
        <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.filterScroll}
          contentContainerStyle={styles.filterRow}>
          {(['Today', 'Week', 'Month', 'All'] as Period[]).map(p => (
            <Pressable key={p} onPress={() => setPeriod(p)}
              style={[styles.pill, period === p && styles.pillActive]}>
              <Text style={[styles.pillText, period === p && styles.pillTextActive]}>{p}</Text>
            </Pressable>
          ))}
        </ScrollView>
      </LinearGradient>

      <ScrollView contentContainerStyle={styles.body} showsVerticalScrollIndicator={false}>
        {/* Overview row - FOCUSING ON THE SELECTED DAY */}
        <View style={styles.secRow}>
          <Text style={styles.secTitle}>Daily Overview</Text>
          <Text style={styles.secSubtitle}>{format(new Date(selectedDay), 'dd MMM yyyy')}</Text>
        </View>

        <View style={styles.overviewRow}>
          {[
            { label: 'Sessions', value: dayTotals.sess, color: '#4F46E5', bg: '#EEF2FF' },
            { label: 'Present', value: dayTotals.p, color: '#059669', bg: '#ECFDF5' },
            { label: 'Absent', value: dayTotals.a, color: '#EF4444', bg: '#FFF1F2' },
            { label: 'Rate', value: `${dayGrandRate}%`, color: dayGrandRate >= 75 ? '#059669' : '#EF4444', bg: dayGrandRate >= 75 ? '#ECFDF5' : '#FFF1F2' },
          ].map(s => (
            <View key={s.label} style={[styles.ovCard, shadows.sm, { backgroundColor: s.bg }]}>
              <Text style={[styles.ovVal, { color: s.color }]}>{loading ? '—' : s.value}</Text>
              <Text style={styles.ovLbl}>{s.label}</Text>
            </View>
          ))}
        </View>

        {/* Trend Chart */}
        <View style={[styles.chartCard, shadows.sm]}>
          <View style={styles.chartTop}>
            <View>
              <Text style={styles.chartTitle}>Attendance Trend</Text>
              <Text style={styles.chartSub}>{dailyPoints.length} day{dailyPoints.length !== 1 ? 's' : ''} in {period.toLowerCase()} period</Text>
            </View>
            <Pressable onPress={fetchData}>
              <MaterialIcons name="refresh" size={22} color="#94A3B8" />
            </Pressable>
          </View>
          {loading
            ? <ActivityIndicator color={colors.primaryBlue} style={{ marginVertical: 40 }} />
            : <View style={{ alignItems: 'center' }}>
                <Svg height={CHART_HEIGHT} width={svgW} viewBox={`0 0 ${svgW} ${CHART_HEIGHT}`}>
                  {/* Grid Lines & Labels */}
                  {[0, 0.25, 0.5, 0.75, 1].map(v => {
                    const y = getY(v * 100);
                    return (
                      <G key={v}>
                        <Path 
                          d={`M ${PADDING} ${y} H ${svgW - PADDING}`} 
                          stroke="#F1F5F9" 
                          strokeWidth="1" 
                          strokeDasharray="4 4"
                        />
                        {v > 0 && (
                          <SvgText
                            x={PADDING - 5}
                            y={y + 3}
                            fontSize="9"
                            fill="#94A3B8"
                            textAnchor="end"
                            fontWeight="600"
                          >
                            {Math.round(v * 100)}%
                          </SvgText>
                        )}
                      </G>
                    );
                  })}

                  {/* Area Fill Gradient */}
                  <Defs>
                    <SvgGradient id="areaGrad" x1="0" y1="0" x2="0" y2="1">
                      <Stop offset="0" stopColor={colors.primaryBlue} stopOpacity="0.3" />
                      <Stop offset="1" stopColor={colors.primaryBlue} stopOpacity="0" />
                    </SvgGradient>
                  </Defs>

                  {/* Horizontal Baseline (X-Axis) */}
                  <Path 
                    d={`M ${PADDING} ${CHART_HEIGHT - 30} H ${svgW - PADDING}`} 
                    stroke="#E2E8F0" 
                    strokeWidth="2" 
                  />

                  {/* Area Fill */}
                  {points.length > 0 && (
                    <Path
                      d={`${areaPath}`}
                      fill="url(#areaGrad)"
                    />
                  )}

                  {/* Main Trend Line connecting from origin */}
                  {points.length > 0 && (
                    <Path
                      d={`M ${PADDING} ${CHART_HEIGHT - 30} ${linePath.replace('M', 'L')}`}
                      stroke={colors.primaryBlue}
                      strokeWidth="3"
                      fill="none"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                  )}

                  {/* Points (with glow, drop lines, and value labels) */}
                  {points.map((p, i) => {
                    const isSel = dailyPoints[i]?.fullDate === selectedDay;
                    const rateVal = dailyPoints[i]?.rate;
                    const baseLine = CHART_HEIGHT - 30;
                    
                    return (
                      <G key={i} onPress={() => setSelectedDay(dailyPoints[i].fullDate)}>
                        {/* Drop Line from 0% */}
                        <Path 
                          d={`M ${p.x} ${baseLine} L ${p.x} ${p.y}`} 
                          stroke={colors.primaryBlue} 
                          strokeWidth="1.5" 
                          strokeDasharray="4 4"
                          opacity={isSel ? 0.6 : 0.2}
                        />

                        {/* Interactive focus area */}
                        <Rect x={p.x - 20} y={0} width={40} height={CHART_HEIGHT} fill="transparent" />
                        
                        {/* Outer Glow Ring */}
                        {isSel && (
                          <Circle cx={p.x} cy={p.y} r="10" fill={colors.primaryBlue} opacity="0.15" />
                        )}
                        
                        {/* Main Point */}
                        <Circle 
                          cx={p.x} cy={p.y} r={isSel ? "6" : "4"} 
                          fill="#FFF" stroke={colors.primaryBlue} strokeWidth={isSel ? "3" : "2"} 
                        />

                        {/* Value Label above point */}
                        {isSel && (
                          <SvgText 
                            x={p.x} y={p.y - 12} 
                            fontSize="11" fontWeight="900" fill={colors.primaryBlue} 
                            textAnchor="middle"
                          >
                            {rateVal}%
                          </SvgText>
                        )}
                      </G>
                    );
                  })}

                  {/* X-Axis Labels */}
                  {dailyPoints.map((p, i) => {
                    const x = getX(i);
                    const y = getY(p.rate);
                    const showLabel = dailyPoints.length < 10 || i % Math.ceil(dailyPoints.length / 7) === 0;
                    return (
                      <React.Fragment key={i}>
                        {/* Point Marker */}
                        <Circle cx={x} cy={y} r="4" fill="#FFF" stroke={colors.primaryBlue} strokeWidth="2" />
                        
                        {/* X-Axis Labels */}
                        {showLabel && (
                          <G>
                            <SvgText
                              x={x}
                              y={CHART_HEIGHT - 10}
                              fontSize="10"
                              fill="#64748B"
                              textAnchor="middle"
                              fontWeight="600"
                            >
                              {p.label}
                            </SvgText>
                          </G>
                        )}
                      </React.Fragment>
                    );
                  })}

                  {/* Gradient Definition */}
                  <Defs>
                    <SvgGradient id="areaGrad" x1="0" y1="0" x2="0" y2="1">
                      <Stop offset="0" stopColor={colors.primaryBlue} stopOpacity="0.4" />
                      <Stop offset="1" stopColor={colors.primaryBlue} stopOpacity="0.01" />
                    </SvgGradient>
                  </Defs>
                </Svg>
              </View>
          }
        </View>

        {/* Short Class Reports */}
        <View style={styles.secRow}>
          <Text style={styles.secTitle}>Class Reports</Text>
          <View style={styles.countPill}>
            <Text style={styles.countPillText}>{classReports.length}</Text>
          </View>
        </View>

        {loading
          ? <ActivityIndicator color={colors.primaryBlue} style={{ marginVertical: 24 }} />
          : classReports.length === 0
            ? <View style={[styles.emptyCard, shadows.sm]}>
                <MaterialIcons name="event-note" size={40} color="#CBD5E1" />
                <Text style={styles.emptyTitle}>No records for this period</Text>
                <Text style={styles.emptyDesc}>Switch to a different time filter.</Text>
              </View>
            : classReports.map((cls, idx) => {
                const pal = [
                  { bg: '#EEF2FF', color: '#4F46E5' },
                  { bg: '#ECFDF5', color: '#059669' },
                  { bg: '#EFF6FF', color: '#2563EB' },
                  { bg: '#FFF7ED', color: '#D97706' },
                ][idx % 4];
                const good = cls.rate >= 75;
                return (
                  <View key={`${cls.className}-${idx}`} style={[styles.clsCard, shadows.sm]}>
                    <View style={styles.clsTop}>
                      <View style={[styles.clsBadge, { backgroundColor: pal.bg, overflow: 'hidden' }]}>
                        {cls.advisorImage ? (
                          <Image source={{ uri: cls.advisorImage }} style={{ width: '100%', height: '100%' }} />
                        ) : (
                          <MaterialIcons name="class" size={18} color={pal.color} />
                        )}
                      </View>
                      <View style={styles.clsInfo}>
                        <Text style={styles.clsName}>{cls.className}</Text>
                        <Text style={styles.clsMeta}>
                          Marked by {cls.markedBy}  ·  {cls.sessions} session{cls.sessions !== 1 ? 's' : ''}
                        </Text>
                      </View>
                      <View style={[styles.rateBadge, { backgroundColor: good ? '#ECFDF5' : '#FFF1F2' }]}>
                        <Text style={[styles.rateText, { color: good ? '#059669' : '#EF4444' }]}>
                          {cls.rate}%
                        </Text>
                      </View>
                    </View>

                    {/* Stats bar */}
                    <View style={styles.clsStats}>
                      <View style={styles.stuStatItem}>
                        <View style={[styles.statDot, { backgroundColor: '#10B981' }]} />
                        <Text style={styles.statLbl}>Present</Text>
                        <Text style={styles.statVal}>{cls.present}</Text>
                      </View>
                      <View style={styles.stuStatItem}>
                        <View style={[styles.statDot, { backgroundColor: '#EF4444' }]} />
                        <Text style={styles.statLbl}>Absent</Text>
                        <Text style={styles.statVal}>{cls.absent}</Text>
                      </View>
                      <View style={styles.stuStatItem}>
                        <View style={[styles.statDot, { backgroundColor: '#F59E0B' }]} />
                        <Text style={styles.statLbl}>On Duty</Text>
                        <Text style={styles.statVal}>{cls.onDuty}</Text>
                      </View>
                      <Pressable onPress={() => downloadClassReport(cls)} style={styles.miniDlBtn}>
                        <MaterialIcons name="download" size={16} color={colors.primaryBlue} />
                        <Text style={styles.miniDlText}>PDF</Text>
                      </Pressable>
                    </View>

                    {/* Attendance bar */}
                    {cls.total > 0 && (
                      <View style={styles.attBarBg}>
                        <View style={[styles.attBarFill, { width: `${cls.rate}%` as any,
                          backgroundColor: good ? '#10B981' : '#EF4444' }]} />
                      </View>
                    )}
                  </View>
                );
              })
        }

        {/* Overall + download CTA */}
        <LinearGradient colors={[colors.primaryBlue, '#1E40AF']} start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }}
          style={[styles.ctaCard, shadows.md]}>
          <View style={styles.ctaContent}>
            <Text style={styles.ctaTitle}>Download Full Report</Text>
            <Text style={styles.ctaDesc}>
              Export all {filteredLogs.length} attendance records for the {period} period as a PDF.
            </Text>
            <Pressable onPress={downloadReport} style={[styles.ctaBtn, downloading && { opacity: 0.6 }]} disabled={downloading}>
              {downloading
                ? <ActivityIndicator color={colors.primaryBlue} size="small" />
                : <Text style={styles.ctaBtnText}>Generate PDF</Text>
              }
            </Pressable>
          </View>
          <View style={styles.ctaIconWrap}>
            <MaterialIcons name="insert-chart" size={80} color="rgba(255,255,255,0.1)" />
          </View>
        </LinearGradient>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#F1F5F9' },
  header: { paddingBottom: spacing.md },
  topBar: {
    flexDirection: 'row', justifyContent: 'space-between',
    alignItems: 'center', paddingHorizontal: spacing.md, paddingBottom: spacing.sm,
  },
  headerSub: { fontSize: 11, color: 'rgba(255,255,255,0.45)', fontWeight: '500' },
  headerTitle: { fontSize: 19, fontWeight: 'bold', color: '#FFF', marginTop: 2 },
  dlBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    backgroundColor: `${colors.primaryBlue}`, paddingHorizontal: 14,
    paddingVertical: 10, borderRadius: 12,
  },
  dlBtnText: { color: '#FFF', fontWeight: 'bold', fontSize: 13 },
  filterScroll: { paddingBottom: spacing.sm },
  filterRow: { paddingHorizontal: spacing.md, gap: spacing.sm },
  pill: {
    paddingHorizontal: 18, paddingVertical: 8, borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  pillActive: { backgroundColor: colors.primaryBlue },
  pillText: { color: 'rgba(255,255,255,0.6)', fontSize: 13, fontWeight: '600' },
  pillTextActive: { color: '#FFF' },
  body: { paddingHorizontal: spacing.md, paddingTop: spacing.lg, paddingBottom: 160 },
  overviewRow: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.lg },
  ovCard: {
    flex: 1, borderRadius: 14, padding: spacing.sm,
    alignItems: 'center', gap: 3,
  },
  ovVal: { fontSize: 18, fontWeight: 'bold' },
  ovLbl: { fontSize: 9, color: '#64748B', fontWeight: '600' },
  chartCard: {
    backgroundColor: '#FFF', borderRadius: borderRadius.xl,
    padding: spacing.md, marginBottom: spacing.xl,
  },
  chartTop: {
    flexDirection: 'row', justifyContent: 'space-between',
    alignItems: 'flex-start', marginBottom: spacing.md,
  },
  chartTitle: { fontSize: 16, fontWeight: 'bold', color: '#0F172A' },
  chartSub: { fontSize: 11, color: '#64748B', marginTop: 2 },
  secRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 24, marginBottom: 12, paddingHorizontal: 4 },
  secTitle: { fontSize: 16, fontWeight: '800', color: '#1E293B', letterSpacing: -0.3 },
  secSubtitle: { fontSize: 13, fontWeight: '600', color: '#64748B' },
  countPill: {
    backgroundColor: colors.primaryBlue, paddingHorizontal: 10,
    paddingVertical: 3, borderRadius: 20,
  },
  countPillText: { fontSize: 11, fontWeight: 'bold', color: '#FFF' },
  emptyCard: {
    backgroundColor: '#FFF', borderRadius: borderRadius.xl,
    padding: spacing.xl, alignItems: 'center', gap: spacing.sm,
  },
  emptyTitle: { fontSize: 15, fontWeight: 'bold', color: '#0F172A' },
  emptyDesc: { fontSize: 13, color: '#94A3B8', textAlign: 'center' },
  clsCard: {
    backgroundColor: '#FFF', borderRadius: borderRadius.xl,
    padding: spacing.md, marginBottom: spacing.sm,
  },
  clsTop: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginBottom: spacing.sm },
  clsBadge: { width: 44, height: 44, borderRadius: 12, justifyContent: 'center', alignItems: 'center' },
  clsInfo: { flex: 1 },
  clsName: { fontSize: 15, fontWeight: '700', color: '#0F172A' },
  clsMeta: { fontSize: 11, color: '#64748B', marginTop: 2 },
  rateBadge: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 10 },
  rateText: { fontSize: 13, fontWeight: 'bold' },
  clsStats: {
    flexDirection: 'row', alignItems: 'center', gap: spacing.md,
    marginBottom: spacing.sm,
  },
  stuStatItem: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  statDot: { width: 8, height: 8, borderRadius: 4 },
  statLbl: { fontSize: 11, color: '#64748B' },
  statVal: { fontSize: 12, fontWeight: 'bold', color: '#0F172A' },
  miniDlBtn: {
    marginLeft: 'auto',
    flexDirection: 'row', alignItems: 'center', gap: 4,
    paddingHorizontal: 10, paddingVertical: 5,
    backgroundColor: `${colors.primaryBlue}10`,
    borderRadius: 8,
  },
  miniDlText: { fontSize: 11, fontWeight: 'bold', color: colors.primaryBlue },
  attBarBg: {
    height: 5, backgroundColor: '#F1F5F9',
    borderRadius: 3, overflow: 'hidden',
  },
  attBarFill: { height: '100%', borderRadius: 3 },
  ctaCard: {
    borderRadius: borderRadius.xl, marginTop: spacing.xl,
    overflow: 'hidden', position: 'relative',
  },
  ctaContent: { padding: spacing.xl, zIndex: 1 },
  ctaTitle: { fontSize: 18, fontWeight: 'bold', color: '#FFF', marginBottom: 8 },
  ctaDesc: { fontSize: 13, color: 'rgba(255,255,255,0.8)', lineHeight: 18, marginBottom: 20 },
  ctaBtn: {
    backgroundColor: '#FFF', paddingHorizontal: 22,
    paddingVertical: 10, borderRadius: 10, alignSelf: 'flex-start',
  },
  ctaBtnText: { color: colors.primaryBlue, fontWeight: 'bold', fontSize: 14 },
  ctaIconWrap: { position: 'absolute', right: -10, bottom: -10, opacity: 0.5 },
  gridLabel: { fontSize: 9, color: '#94A3B8' },
});
