import React, { useState, useEffect, useCallback, useMemo } from 'react';
import {
  View, Text, StyleSheet, ScrollView, Pressable,
  Dimensions, ActivityIndicator, Alert, Image,
} from 'react-native';
import { Download, Calendar, RefreshCcw, FileText, TrendingUp, Users, School, AlertCircle, BadgeCheck, Activity, User, ChevronLeft } from 'lucide-react-native';
import Animated, { FadeInDown, FadeInUp, FadeInRight, useAnimatedProps, useSharedValue, withTiming, withDelay, Easing } from 'react-native-reanimated';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { LinearGradient } from 'expo-linear-gradient';
import { Svg, Path, G, Text as SvgText, Defs, LinearGradient as SvgGradient, Stop, Circle, Rect } from 'react-native-svg';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { dataService } from '../../services/dataService';
import { colors, spacing, shadows, gradients } from '../../constants/theme';
import { format, startOfWeek, startOfMonth, isAfter, subDays } from 'date-fns';
import { useAuth } from '../../hooks/useAuth';

const { width } = Dimensions.get('window');

type Period = 'Today' | 'Week' | 'Month';

// ─── Generate HTML for PDF ───────────────────────────────────
const buildHTML = (logs: any[], period: string, stats: any, deptName: string) => `
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: 'Helvetica Neue', sans-serif; margin: 0; padding: 32px; background: #F8FAFC; color: #0F172A; }
  h1 { font-size: 26px; margin: 0 0 4px; }
  .sub { font-size: 13px; color: #64748B; margin-bottom: 24px; }
  .summary { display: flex; gap: 16px; margin-bottom: 24px; }
  .stat-box { background: #EEF2FF; padding: 14px 20px; border-radius: 12px; flex: 1; text-align: center; }
  .stat-val { font-size: 28px; font-weight: bold; color: #4F46E5; }
  .stat-lbl { font-size: 11px; color: #64748B; text-transform: uppercase; }
  table { width: 100%; border-collapse: collapse; background: #FFF; border-radius: 12px; overflow: hidden; }
  th { background: #0F172A; color: #FFF; padding: 12px 16px; font-size: 12px; text-align: left; }
  td { padding: 12px 16px; border-bottom: 1px solid #F1F5F9; font-size: 13px; }
  .good { color: #059669; font-weight: bold; }
  .bad { color: #EF4444; font-weight: bold; }
  .footer { margin-top: 24px; font-size: 11px; color: #94A3B8; text-align: center; }
</style>
</head>
<body>
  <h1>${deptName} Attendance Report</h1>
  <p class="sub">Period: ${period} &nbsp;·&nbsp; Generated ${format(new Date(), 'dd MMM yyyy, hh:mm a')}</p>
  <div class="summary">
    <div class="stat-box"><div class="stat-val">${stats.totalClasses}</div><div class="stat-lbl">Classes</div></div>
    <div class="stat-box"><div class="stat-val">${stats.presentToday}</div><div class="stat-lbl">Present Today</div></div>
    <div class="stat-box"><div class="stat-val">${stats.absentToday}</div><div class="stat-lbl">Absent Today</div></div>
  </div>
  <table>
    <tr><th>Class</th><th>Date</th><th>Marked By</th><th>Present</th><th>Absent</th><th>On Duty</th><th>Rate</th></tr>
    ${logs.map(l => {
      const r = l.totalStudents > 0 ? Math.round(((l.present + l.onDuty) / l.totalStudents) * 100) : 0;
      return `<tr>
        <td>${l.className}</td>
        <td>${l.date}</td>
        <td>${l.markedBy}</td>
        <td class="good">${l.present}</td>
        <td class="bad">${l.absent}</td>
        <td>${l.onDuty}</td>
        <td class="${r >= 75 ? 'good' : 'bad'}">${r}%</td>
      </tr>`;
    }).join('')}
  </table>
  <p class="footer">This report was auto-generated by the Attendance Management System.</p>
</body>
</html>`;

const AnimatedCircle = Animated.createAnimatedComponent(Circle);

export default function DepartmentReport() {
  const insets = useSafeAreaInsets();
  const router = useRouter();
  const { departmentId, departmentName } = useLocalSearchParams();
  const [period, setPeriod] = useState<Period>('Week');
  const [selectedDay, setSelectedDay] = useState<string>(format(new Date(), 'yyyy-MM-dd'));
  const [allLogs, setAllLogs] = useState<any[]>([]);
  const [stats, setStats] = useState({ totalClasses: 0, presentToday: 0, absentToday: 0, onDutyToday: 0 });
  const [loading, setLoading] = useState(true);
  const [downloading, setDownloading] = useState(false);

  const deptId = departmentId as string;
  const deptName = (departmentName as string) || 'Department';

  // Animation values
  const progress = useSharedValue(0);

  const fetchData = useCallback(async () => {
    try {
      setLoading(true);
      // Pass deptId to fetch departmental specific data
      const [logs, st] = await Promise.all([
        dataService.getAttendanceLogs(500, deptId),
        dataService.getStatistics(deptId),
      ]);
      setAllLogs(logs);
      setStats(st);
      
      const today = format(new Date(), 'yyyy-MM-dd');
      setSelectedDay(today);
    } catch (e) {
      console.error('Reports fetch error:', e);
    } finally {
      setLoading(false);
    }
  }, [deptId]);

  useEffect(() => {
    fetchData();
    const subAttendance = dataService.subscribeToTable('attendance_records', fetchData);
    const subClasses = dataService.subscribeToTable('classes', fetchData);
    
    return () => {
      subAttendance?.unsubscribe();
      subClasses?.unsubscribe();
    };
  }, [fetchData]);


  // 1. Calculations first
  const filteredLogs = useMemo(() => allLogs.filter(l => {
    try {
      if (!l.date) return false;
      const now = new Date();
      const todayStr = format(now, 'yyyy-MM-dd');
      
      if (period === 'Today') return l.date.substring(0, 10) === todayStr;
      
      const logDate = new Date(l.date);
      if (period === 'Week') return isAfter(logDate, startOfWeek(now, { weekStartsOn: 1 }));
      if (period === 'Month') return isAfter(logDate, startOfMonth(now));
      return false;
    } catch { return false; }
  }), [allLogs, period]);

  const focusLogs = useMemo(() => filteredLogs.filter(l => (l.date || '').substring(0, 10) === selectedDay), [filteredLogs, selectedDay]);

  const periodTotals = useMemo(() => filteredLogs.reduce((s, l) => ({
    p: s.p + (l.present || 0),
    a: s.a + (l.absent || 0),
    o: s.o + (l.onDuty || 0),
    tot: s.tot + (l.totalStudents || (l.present + l.absent + (l.onDuty || 0))),
    sess: s.sess + 1
  }), { p: 0, a: 0, o: 0, tot: 0, sess: 0 }), [filteredLogs]);

  const periodGrandRate = useMemo(() => periodTotals.tot > 0
    ? Math.round(((periodTotals.p + periodTotals.o) / periodTotals.tot) * 100) : 0, [periodTotals]);

  const dayTotals = useMemo(() => focusLogs.reduce((s, l) => ({
    p: s.p + (l.present || 0),
    a: s.a + (l.absent || 0),
    o: s.o + (l.onDuty || 0),
    tot: s.tot + (l.totalStudents || (l.present + l.absent + (l.onDuty || 0))),
    sess: s.sess + 1
  }), { p: 0, a: 0, o: 0, tot: 0, sess: 0 }), [focusLogs]);

  const markingCompletion = useMemo(() => {
    if (stats.totalClasses === 0) return 0;
    return Math.round((dayTotals.sess / stats.totalClasses) * 100);
  }, [dayTotals.sess, stats.totalClasses]);

  const classReports = useMemo(() => {
    const classSummary: Record<string, { logs: any[]; className: string; markedBy: string; advisorImage?: string }> = {};
    focusLogs.forEach(l => {
      const cn = l.className || 'Unknown';
      if (!classSummary[cn]) {
        classSummary[cn] = { logs: [], className: cn, markedBy: l.markedBy, advisorImage: l.advisorImage };
      }
      classSummary[cn].logs.push(l);
    });

    return Object.values(classSummary).map(c => {
      const totalP = c.logs.reduce((s, l) => s + (l.present || 0), 0);
      const totalA = c.logs.reduce((s, l) => s + (l.absent || 0), 0);
      const totalO = c.logs.reduce((s, l) => s + (l.onDuty || 0), 0);
      const total = totalP + totalA + totalO;
      const rate = total > 0 ? Math.round(((totalP + totalO) / total) * 100) : 0;
      return { 
        className: c.className, 
        markedBy: c.markedBy, 
        advisorImage: c.advisorImage,
        present: totalP, 
        absent: totalA, 
        onDuty: totalO, 
        total, 
        rate, 
        sessions: c.logs.length 
      };
    });
  }, [focusLogs]);

  useEffect(() => {
    if (!loading) {
      progress.value = withDelay(500, withTiming(periodGrandRate / 100, {
        duration: 1500,
        easing: Easing.out(Easing.exp)
      }));
    }
  }, [loading, periodGrandRate, progress]);

  const animatedProps = useAnimatedProps(() => {
    const circumference = 2 * Math.PI * 45;
    return {
      strokeDashoffset: circumference - progress.value * circumference,
    };
  });

  const dailyPoints = useMemo(() => {
    const now = new Date();
    if (period === 'Today') {
      const dKey = format(now, 'yyyy-MM-dd');
      let p=0, a=0, o=0;
      allLogs.forEach(l => {
        if ((l.date || '').startsWith(dKey)) {
          p += (l.present || 0); a += (l.absent || 0); o += (l.onDuty || 0);
        }
      });
      const t = p + a + o;
      return [{
        rate: t > 0 ? Math.round(((p + o) / t) * 100) : -1,
        label: format(now, 'dd MMM'),
        day: format(now, 'EEE'),
        fullDate: dKey
      }];
    }

    if (period === 'Week') {
      const days = [];
      for (let i = 6; i >= 0; i--) {
        const d = subDays(now, i);
        const dKey = format(d, 'yyyy-MM-dd');
        let p=0, a=0, o=0;
        allLogs.forEach(l => {
          if ((l.date || '').startsWith(dKey)) {
            p += (l.present || 0); a += (l.absent || 0); o += (l.onDuty || 0);
          }
        });
        const t = p + a + o;
        days.push({
          rate: t > 0 ? Math.round(((p + o) / t) * 100) : -1,
          label: format(d, 'EEE dd').toLowerCase(),
          day: format(d, 'EEE'),
          fullDate: dKey
        });
      }
      return days;
    }

    if (period === 'Month') {
      const weeks = [];
      for (let i = 3; i >= 0; i--) {
        let p=0, a=0, o=0;
        const weekEnd = subDays(now, i * 7);
        const weekStart = subDays(weekEnd, 6);
        let weekLabel = `W${4-i}`; 
        allLogs.forEach(l => {
          const logDate = new Date(l.date);
          if (l.date && !isNaN(logDate.getTime())) {
            if (isAfter(logDate, subDays(weekStart, 1)) && !isAfter(logDate, weekEnd)) {
              p += (l.present || 0); a += (l.absent || 0); o += (l.onDuty || 0);
            }
          }
        });
        const t = p + a + o;
        weeks.push({
          rate: t > 0 ? Math.round(((p + o) / t) * 100) : -1,
          label: weekLabel,
          day: weekLabel,
          fullDate: format(weekEnd, 'yyyy-MM-dd')
        });
      }
      return weeks;
    }
    return [];
  }, [allLogs, period]);

  const svgW = width - 48;
  const CHART_HEIGHT = 160;
  const PADDING = 20;

  const getX = useCallback((index: number) => {
    if (dailyPoints.length <= 1) return svgW / 2;
    return PADDING + (index / (dailyPoints.length - 1)) * (svgW - PADDING * 2);
  }, [dailyPoints.length, svgW]);

  const getY = useCallback((rate: number) => {
    return (CHART_HEIGHT - 45) - (rate / 100) * (CHART_HEIGHT - 70) + 5;
  }, []);

  const points = useMemo(() => dailyPoints.map((p, i) => ({ x: getX(i), y: getY(p.rate) })), [dailyPoints, getX, getY]);

  const linePath = useMemo(() => {
    if (points.length === 0) return '';
    return points.map((p, i) => `${i === 0 ? 'M' : 'L'} ${p.x} ${p.y}`).join(' ');
  }, [points]);

  const areaPath = useMemo(() => {
    if (points.length === 0) return '';
    const baseLine = CHART_HEIGHT - 30;
    return `M ${PADDING} ${baseLine} ${linePath.replace('M', 'L')} L ${points[points.length - 1].x} ${baseLine} Z`;
  }, [points, linePath]);

  const downloadReport = async () => {
    try {
      setDownloading(true);
      const html = buildHTML(filteredLogs, period, stats, deptName);
      const { uri } = await Print.printToFileAsync({ html });
      const canShare = await Sharing.isAvailableAsync();
      if (canShare) {
        await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
      } else {
        Alert.alert('Downloaded', `Report saved to:\n${uri}`);
      }
    } catch (e: any) {
      Alert.alert('Error', e?.message || 'Failed to generate report.');
    } finally { setDownloading(false); }
  };

  const downloadClassReport = async (cls: any) => {
    try {
      const html = buildHTML(filteredLogs.filter(l => l.className === cls.className), period, {
        totalClasses: 1, presentToday: cls.present, absentToday: cls.absent,
      }, deptName);
      const { uri } = await Print.printToFileAsync({ html });
      const canShare = await Sharing.isAvailableAsync();
      if (canShare) await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
    } catch (e: any) { Alert.alert('Error', e?.message || 'Failed.'); }
  };

  return (
    <View style={styles.root}>
      {/* ── Premium Header ── */}
      <View style={styles.headerContainer}>
        <LinearGradient colors={gradients.premium as any} style={[styles.headerGradient, { paddingTop: insets.top + 10 }]}>
          
          <View style={styles.topBar}>
            <View style={{ flexDirection: 'row', alignItems: 'center' }}>
              <Pressable onPress={() => router.back()} style={styles.backBtn}>
                <ChevronLeft size={24} color="#FFF" />
              </Pressable>
              <Animated.View entering={FadeInDown.delay(100).duration(800)}>
                <Text style={styles.welcomeTxt}>{deptName}</Text>
                <Text style={styles.headerTitle}>Trend Analysis</Text>
              </Animated.View>
            </View>
            <View style={styles.headerActions}>
              <Pressable onPress={downloadReport} style={styles.actionBtn}>
                <Download size={20} color="#FFF" />
              </Pressable>
              <Pressable onPress={fetchData} style={styles.actionBtn}>
                <RefreshCcw size={20} color="#FFF" />
              </Pressable>
            </View>
          </View>

          <View style={styles.headerMainContent}>
            {/* Gauge */}
            <Animated.View entering={FadeInRight.delay(200).duration(1000)} style={styles.gaugeSection}>
              <Svg height="120" width="120" viewBox="0 0 100 100">
                <Circle cx="50" cy="50" r="45" stroke="rgba(255,255,255,0.1)" strokeWidth="6" fill="none" />
                <AnimatedCircle
                  cx="50" cy="50" r="45"
                  stroke="#10B981" strokeWidth="8" fill="none"
                  strokeDasharray={`${2 * Math.PI * 45}`}
                  animatedProps={animatedProps}
                  strokeLinecap="round" transform="rotate(-90 50 50)"
                />
                <SvgText x="50" y="48" fontSize="22" fontWeight="900" fill="#FFF" textAnchor="middle">
                  {loading ? '—' : `${periodGrandRate}%`}
                </SvgText>
                <SvgText x="50" y="65" fontSize="8" fontWeight="600" fill="rgba(255,255,255,0.4)" textAnchor="middle">
                  ATTENDANCE
                </SvgText>
              </Svg>
            </Animated.View>

            {/* Quick Stats Grid */}
            <View style={styles.headerStatsGrid}>
              <Animated.View entering={FadeInDown.delay(300).duration(800)} style={styles.headerStatCard}>
                <BadgeCheck size={16} color="#10B981" />
                <Text style={styles.headerStatVal}>{markingCompletion}%</Text>
                <Text style={styles.headerStatLbl}>MarkingDone</Text>
              </Animated.View>
              <Animated.View entering={FadeInDown.delay(400).duration(800)} style={styles.headerStatCard}>
                <Users size={16} color="rgba(255,255,255,0.4)" />
                <Text style={styles.headerStatVal}>{periodTotals.p}</Text>
                <Text style={styles.headerStatLbl}>Present</Text>
              </Animated.View>
              <Animated.View entering={FadeInDown.delay(500).duration(800)} style={styles.headerStatCard}>
                <AlertCircle size={16} color="rgba(255,255,255,0.4)" />
                <Text style={styles.headerStatVal}>{periodTotals.a}</Text>
                <Text style={styles.headerStatLbl}>Absent</Text>
              </Animated.View>
              <Animated.View entering={FadeInDown.delay(600).duration(800)} style={styles.headerStatCard}>
                <School size={16} color="rgba(255,255,255,0.4)" />
                <Text style={styles.headerStatVal}>{stats.totalClasses}</Text>
                <Text style={styles.headerStatLbl}>Total Cls</Text>
              </Animated.View>
            </View>
          </View>
        </LinearGradient>

        {/* Floating Filter Pills */}
        <Animated.View entering={FadeInUp.delay(600).duration(800)} style={[styles.floatingFilters, shadows.premium]}>
          {(['Today', 'Week', 'Month'] as Period[]).map((p) => (
            <Pressable key={p} onPress={() => {
              setPeriod(p);
              if (p === 'Today') setSelectedDay(format(new Date(), 'yyyy-MM-dd'));
            }}
              style={[styles.filterPill, period === p && styles.filterPillActive]}>
              <Text style={[styles.filterPillText, period === p && styles.filterPillTextActive]}>{p}</Text>
            </Pressable>
          ))}
        </Animated.View>
      </View>

      <ScrollView contentContainerStyle={styles.body} showsVerticalScrollIndicator={false}>
        <Animated.View entering={FadeInDown.delay(700).duration(800)} style={styles.dayHeader}>
          <View>
            <Text style={styles.secTitle}>Daily Overview</Text>
            <Text style={styles.secSubtitle}>{format(new Date(selectedDay), 'EEEE, dd MMMM yyyy')}</Text>
          </View>
          <View style={styles.dayAction}>
             <Calendar size={18} color={colors.primaryBlue} />
          </View>
        </Animated.View>

        <View style={styles.reportSummaryPanel}>
          <View style={styles.summaryItem}>
            <View style={styles.summaryIcon}><Activity size={18} color={colors.primaryBlue} /></View>
            <View style={{ flex: 1 }}>
              <Text style={styles.summaryLbl}>Marking Status</Text>
              <Text style={styles.summaryVal}>{dayTotals.sess} of {stats.totalClasses} Classes Done</Text>
            </View>
            <Text style={{ fontSize: 13, fontWeight: '800', color: markingCompletion >= 100 ? '#10B981' : '#64748B' }}>
              {markingCompletion}%
            </Text>
          </View>
          <View style={[styles.summaryDivider, { marginVertical: 12 }]} />
          <View style={styles.summaryGrid}>
             <View style={styles.summaryStat}><Text style={styles.statSubVal}>{dayTotals.p}</Text><Text style={styles.statSubLbl}>Present</Text></View>
             <View style={styles.summaryVerticalDivider} />
             <View style={styles.summaryStat}><Text style={styles.statSubVal}>{dayTotals.a}</Text><Text style={styles.statSubLbl}>Absent</Text></View>
             <View style={styles.summaryVerticalDivider} />
             <View style={styles.summaryStat}><Text style={styles.statSubVal}>{dayTotals.o}</Text><Text style={styles.statSubLbl}>On Duty</Text></View>
          </View>
        </View>

        {/* Trend Chart */}
        <View style={[styles.chartCard, shadows.sm]}>
          <View style={styles.chartTop}>
            <View>
              <Text style={styles.chartTitle}>Attendance Trend</Text>
              <Text style={styles.chartSub}>{dailyPoints.length} day{dailyPoints.length !== 1 ? 's' : ''} in {period.toLowerCase()} period</Text>
            </View>
            <Pressable onPress={fetchData}><RefreshCcw size={20} color="#94A3B8" /></Pressable>
          </View>
          {loading
            ? <ActivityIndicator color={colors.primaryBlue} style={{ marginVertical: 40 }} />
            : <View style={{ alignItems: 'center' }}>
                <Svg height={CHART_HEIGHT} width={svgW} viewBox={`0 0 ${svgW} ${CHART_HEIGHT}`}>
                  {[0, 0.25, 0.5, 0.75, 1].map(v => {
                    const y = getY(v * 100);
                    return (
                      <G key={v}>
                        <Path d={`M ${PADDING} ${y} H ${svgW - PADDING}`} stroke="#F1F5F9" strokeWidth="1" strokeDasharray="4 4" />
                        {v > 0 && <SvgText x={PADDING - 5} y={y + 3} fontSize="9" fill="#94A3B8" textAnchor="end" fontWeight="600">{Math.round(v * 100)}%</SvgText>}
                      </G>
                    );
                  })}
                  <Defs>
                    <SvgGradient id="areaGrad" x1="0" y1="0" x2="0" y2="1">
                      <Stop offset="0" stopColor={colors.primaryBlue} stopOpacity="0.3" />
                      <Stop offset="1" stopColor={colors.primaryBlue} stopOpacity="0" />
                    </SvgGradient>
                  </Defs>
                  <Path d={`M ${PADDING} ${CHART_HEIGHT - 30} H ${svgW - PADDING}`} stroke="#E2E8F0" strokeWidth="2" />
                  {points.length > 0 && <Path d={`${areaPath}`} fill="url(#areaGrad)" />}
                  {points.length > 0 && points.some(p => p.y < CHART_HEIGHT - 30) && (
                    <Path d={`M ${PADDING} ${CHART_HEIGHT - 30} ${linePath.replace('M', 'L')}`}
                      stroke={colors.primaryBlue} strokeWidth="3" fill="none" strokeLinecap="round" strokeLinejoin="round"
                    />
                  )}
                  {points.map((p, i) => {
                    if (dailyPoints[i].rate < 0) return null;
                    const isSel = dailyPoints[i]?.fullDate === selectedDay;
                    return (
                      <G key={i} onPress={() => setSelectedDay(dailyPoints[i].fullDate)}>
                        <Path d={`M ${p.x} ${CHART_HEIGHT - 30} L ${p.x} ${p.y}`} stroke={colors.primaryBlue} strokeWidth="1.5" strokeDasharray="4 4" opacity={isSel ? 0.6 : 0.2} />
                        <Rect x={p.x - 20} y={0} width={40} height={CHART_HEIGHT} fill="transparent" />
                        {isSel && <Circle cx={p.x} cy={p.y} r="10" fill={colors.primaryBlue} opacity="0.15" />}
                        <Circle cx={p.x} cy={p.y} r={isSel ? "6" : "4"} fill="#FFF" stroke={colors.primaryBlue} strokeWidth={isSel ? "3" : "2"} />
                        {isSel && <SvgText x={p.x} y={p.y - 12} fontSize="11" fontWeight="900" fill={colors.primaryBlue} textAnchor="middle">{dailyPoints[i].rate}%</SvgText>}
                      </G>
                    );
                  })}
                  {dailyPoints.map((p, i) => {
                    const x = getX(i);
                    const showLabel = dailyPoints.length < 10 || i % Math.ceil(dailyPoints.length / 7) === 0;
                    return showLabel && <SvgText key={i} x={x} y={CHART_HEIGHT - 10} fontSize="10" fill="#64748B" textAnchor="middle" fontWeight="600">{p.label}</SvgText>;
                  })}
                </Svg>
              </View>
          }
        </View>

        {/* Short Class Reports */}
        <View style={styles.secRow}>
          <Text style={styles.secTitle}>Records Breakdown</Text>
          <View style={styles.countPill}><Text style={styles.countPillText}>{classReports.length}</Text></View>
        </View>

        {loading
          ? <ActivityIndicator color={colors.primaryBlue} style={{ marginVertical: 24 }} />
          : classReports.length === 0
            ? <View style={styles.emptyCard}><FileText size={48} color="#CBD5E1" /><Text style={styles.emptyTitle}>No records</Text></View>
            : classReports.map((cls, idx) => {
                const good = cls.rate >= 75;
                const pal = [{ bg: '#EEF2FF', color: '#4F46E5' }, { bg: '#ECFDF5', color: '#059669' }, { bg: '#EFF6FF', color: '#2563EB' }, { bg: '#FFF7ED', color: '#D97706' }][idx % 4];
                return (
                  <View key={`${cls.className}-${idx}`} style={[styles.clsCard, shadows.sm]}>
                    <View style={styles.clsTop}>
                      <View style={[styles.clsBadge, { backgroundColor: pal.bg }]}>
                        {cls.advisorImage ? <Image source={{ uri: cls.advisorImage }} style={{ width: '100%', height: '100%' }} /> : <User size={20} color={pal.color} />}
                      </View>
                      <View style={styles.clsInfo}>
                         <Text style={styles.clsName}>{cls.className}</Text>
                         <Text style={styles.clsMeta}>Marked by {cls.markedBy} · {cls.sessions} sessions</Text>
                      </View>
                      <View style={[styles.rateBadge, { backgroundColor: good ? '#ECFDF5' : '#FFF1F2' }]}><Text style={[styles.rateText, { color: good ? '#059669' : '#EF4444' }]}>{cls.rate}%</Text></View>
                    </View>
                    <View style={styles.clsStats}>
                       {[{ l: 'Present', v: cls.present, c: '#10B981' }, { l: 'Absent', v: cls.absent, c: '#EF4444' }, { l: 'On Duty', v: cls.onDuty, c: '#F59E0B' }].map(s => (
                         <View key={s.l} style={styles.stuStatItem}><View style={[styles.statDot, { backgroundColor: s.c }]} /><Text style={styles.statLbl}>{s.l}</Text><Text style={styles.statVal}>{s.v}</Text></View>
                       ))}
                       <Pressable onPress={() => downloadClassReport(cls)} style={styles.miniDlBtn}><Download size={16} color={colors.primaryBlue} /><Text style={styles.miniDlText}>PDF</Text></Pressable>
                    </View>
                    <View style={styles.attBarBg}><View style={[styles.attBarFill, { width: `${cls.rate}%` as any, backgroundColor: good ? '#10B981' : '#EF4444' }]} /></View>
                  </View>
                );
              })
        }

        <LinearGradient colors={[colors.primaryBlue, '#1E40AF']} start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }} style={[styles.ctaCard, shadows.md]}>
          <View style={styles.ctaContent}>
            <Text style={styles.ctaTitle}>Export {deptName} Report</Text>
            <Text style={styles.ctaDesc}>Download all records for this period as a formal PDF.</Text>
            <Pressable onPress={downloadReport} style={styles.ctaBtn} disabled={downloading}>
              {downloading ? <ActivityIndicator color={colors.primaryBlue} /> : <Text style={styles.ctaBtnText}>Generate PDF</Text>}
            </Pressable>
          </View>
          <View style={styles.ctaIconWrap}><TrendingUp size={80} color="rgba(255,255,255,0.1)" /></View>
        </LinearGradient>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#F8FAFC' },
  headerContainer: { backgroundColor: '#F8FAFC', zIndex: 10 },
  headerGradient: { paddingBottom: 60, borderBottomLeftRadius: 40, borderBottomRightRadius: 40, paddingHorizontal: spacing.lg },
  topBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 25 },
  backBtn: { width: 40, height: 40, borderRadius: 12, backgroundColor: 'rgba(255,255,255,0.1)', justifyContent: 'center', alignItems: 'center', marginRight: 10 },
  welcomeTxt: { fontSize: 13, color: 'rgba(255,255,255,0.5)', fontWeight: '600', letterSpacing: 0.5 },
  headerTitle: { fontSize: 24, fontWeight: '900', color: '#FFF', marginTop: 4 },
  headerActions: { flexDirection: 'row', gap: 10 },
  actionBtn: { width: 40, height: 40, backgroundColor: 'rgba(255,255,255,0.1)', borderRadius: 12, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  headerMainContent: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 20 },
  gaugeSection: { backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 30, padding: 5, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  headerStatsGrid: { flex: 1, flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  headerStatCard: { width: '47%', backgroundColor: 'rgba(255,255,255,0.08)', borderRadius: 18, padding: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  headerStatVal: { fontSize: 18, fontWeight: '900', color: '#FFF' },
  headerStatLbl: { fontSize: 9, color: 'rgba(255,255,255,0.4)', fontWeight: '700', textTransform: 'uppercase' },
  floatingFilters: { position: 'absolute', bottom: -20, left: 20, right: 20, backgroundColor: '#FFF', borderRadius: 20, flexDirection: 'row', padding: 5 },
  filterPill: { flex: 1, paddingVertical: 12, alignItems: 'center', borderRadius: 15 },
  filterPillActive: { backgroundColor: colors.primaryBlue },
  filterPillText: { fontSize: 13, fontWeight: '700', color: '#64748B' },
  filterPillTextActive: { color: '#FFF' },
  body: { padding: 20, paddingTop: 40, paddingBottom: 100 },
  dayHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  secTitle: { fontSize: 18, fontWeight: '900', color: '#0F172A' },
  secSubtitle: { fontSize: 12, color: '#64748B', fontWeight: '600' },
  dayAction: { width: 40, height: 40, backgroundColor: '#EFF6FF', borderRadius: 12, justifyContent: 'center', alignItems: 'center' },
  reportSummaryPanel: { backgroundColor: '#FFF', borderRadius: 24, padding: 20, marginBottom: 20, ...shadows.sm },
  summaryItem: { flexDirection: 'row', alignItems: 'center', gap: 15 },
  summaryIcon: { width: 36, height: 36, backgroundColor: '#EFF6FF', borderRadius: 10, justifyContent: 'center', alignItems: 'center' },
  summaryLbl: { fontSize: 11, color: '#64748B', fontWeight: '700', textTransform: 'uppercase' },
  summaryVal: { fontSize: 14, fontWeight: '800', color: '#0F172A' },
  summaryDivider: { height: 1, backgroundColor: '#F1F5F9' },
  summaryGrid: { flexDirection: 'row', justifyContent: 'space-between' },
  summaryStat: { flex: 1, alignItems: 'center' },
  statSubVal: { fontSize: 18, fontWeight: '900', color: '#0F172A' },
  statSubLbl: { fontSize: 9, color: '#64748B', fontWeight: '800', textTransform: 'uppercase' },
  summaryVerticalDivider: { width: 1, height: 25, backgroundColor: '#F1F5F9' },
  chartCard: { backgroundColor: '#FFF', borderRadius: 24, padding: 20, marginBottom: 20 },
  chartTop: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 },
  chartTitle: { fontSize: 16, fontWeight: '900', color: '#0F172A' },
  chartSub: { fontSize: 11, color: '#64748B', fontWeight: '600' },
  secRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 15 },
  countPill: { backgroundColor: colors.primaryBlue, paddingHorizontal: 10, paddingVertical: 2, borderRadius: 10 },
  countPillText: { fontSize: 11, fontWeight: '900', color: '#FFF' },
  clsCard: { backgroundColor: '#FFF', borderRadius: 24, padding: 15, marginBottom: 15 },
  clsTop: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  clsBadge: { width: 40, height: 40, borderRadius: 12, justifyContent: 'center', alignItems: 'center', overflow: 'hidden' },
  clsInfo: { flex: 1 },
  clsName: { fontSize: 15, fontWeight: '800', color: '#0F172A' },
  clsMeta: { fontSize: 11, color: '#64748B', fontWeight: '600' },
  rateBadge: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 10 },
  rateText: { fontSize: 13, fontWeight: '900' },
  clsStats: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 15, gap: 10 },
  stuStatItem: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 4 },
  statDot: { width: 6, height: 6, borderRadius: 3 },
  statLbl: { fontSize: 9, color: '#64748B', fontWeight: '700' },
  statVal: { fontSize: 11, fontWeight: '800', color: '#0F172A' },
  miniDlBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: '#EFF6FF', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
  miniDlText: { fontSize: 10, fontWeight: '900', color: colors.primaryBlue },
  attBarBg: { height: 6, backgroundColor: '#F1F5F9', borderRadius: 3, marginTop: 15, overflow: 'hidden' },
  attBarFill: { height: '100%', borderRadius: 3 },
  ctaCard: { borderRadius: 30, padding: 25, flexDirection: 'row', overflow: 'hidden' },
  ctaContent: { flex: 1, zIndex: 1 },
  ctaTitle: { fontSize: 20, fontWeight: '900', color: '#FFF' },
  ctaDesc: { fontSize: 13, color: 'rgba(255,255,255,0.7)', marginTop: 8, marginBottom: 20 },
  ctaBtn: { backgroundColor: '#FFF', paddingHorizontal: 20, paddingVertical: 12, borderRadius: 15, alignSelf: 'flex-start' },
  ctaBtnText: { color: colors.primaryBlue, fontWeight: '800', fontSize: 14 },
  ctaIconWrap: { position: 'absolute', right: -20, bottom: -20 },
  emptyCard: { padding: 40, alignItems: 'center', backgroundColor: '#FFF', borderRadius: 24, ...shadows.sm },
  emptyTitle: { fontSize: 16, fontWeight: '800', color: '#64748B', marginTop: 10 }
});
